# using docker compose for prometheus

# version: "3.9"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: aurora-prometheus
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped

